auto: true
markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title
title: alvin.fu
url: http://fupengfei.github.io/alvin.fu
feed: /atom.xml
author_info: <a href="http://fupengfei.github.io/alvin.fu">alvin.fu</a>
