auto: true
markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title
title: alvin.fu
url: http://www.fpfos.com
# url: http://localhost:4000
feed: /atom.xml
author_info: <a href="fpfos.com">alvin.fu</a>
