auto: true
markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title
title: alvin.fu
url: http://fupengfei.github.io/blog
feed: /atom.xml
author_info: <a href="http://fupengfei.github.io/blog">alvin.fu</a>
